language: java
jdk:
  - oraclejdk8
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --batch --yes; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --batch --yes; fi
deploy:
- 
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    repo: fintonic/versioning-spring-boot-starter
    branch: master
    jdk: oraclejdk8
- 
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    repo: fintonic/versioning-spring-boot-starter
    tags: true
    jdk: oraclejdk8
notifications:
  hipchat:
    rooms:
      secure: PIuADhuki5sWCpgefeoJvMBXv0BBblOZ2MztsjMkwL+nrpH9kIGvAlOWZJaUWkwZYNBUCgJEsR7n8gzGhdFahiKChfDnOrGrFzb4WP1fqwvTZ7rndfBoeSVcdazfGQvFOh1DO1pm1ywMpb4iHoX/jipVyUhDRPFLaHCDY/wUTUANGD8feN+OkNSFA7bNp4q4FM7UKO3tAZOG3aKlpEs6sirvykGag/Guc8KeDTnpYfk1LVuK3xWOXuZq+5Phj9JZbvj+WglWQ0t03FAASFFVDyspGwh/0h5VdCqiqtnzxmpgYq58Q0fB5nXAMATpcaEdrckQaRvETe1mkC1D2fPbQHWLSV3hfX2uKiCNv6602pH0u7zduaJvaWfdERIYwaqAWzrc2Iso3kR0s7PUvskTShceGMPXPLOZr5BmYUVA97QT4K/O9/zavLR/2/4WClbNzNibip1AiO1aSe9jyC2qCl7AYnQA4y9W+2A1QZa1RQKqlERaRM0ab51zRFIXaIlU2I0kFp6xPoXVmpk0RXI9I6eju/Vtek0xbW+Pu0lg7W0tEhNfzz0PElgi0ERsh1NskH0XcYQLyT73qJRokcHaLEkcod3iUCJMLuVzwQM26kjxJ2k7wxIuNCKLpszHG3+kOzo72ztWHK0Op09Df0dSFvEeP+dXS1Q90vdWn0U/QtA=
